Import('env', 'platform', 'Prefix')

TARGET = 'sonotopy'

SOURCE = ['BeatTracker.cpp', 'CircleMapCircuit.cpp',
	'CircleMapCircuitParameters.cpp', 'CircleTopology.cpp', 'CircularBuffer.cpp',
	'GridMapCircuit.cpp', 'GridMapCircuitParameters.cpp', 'Normalizer.cpp',
	'SOM.cpp', 'Smoother.cpp', 'SpectrumMap.cpp',
	'SpectrumMapCircuit.cpp', 'SpectrumMapCircuitParameters.cpp',
	'SpectrumAnalyzer.cpp', 'SpectrumBinDivider.cpp',
	'Stopwatch.cpp', 'Topology.cpp', 'RectGridTopology.cpp']
 
CPPPATH = ['../../../include/sonotopy']
env.Append(CPPPATH = CPPPATH)

LibSonotopy = env.StaticLibrary(target = TARGET, source = SOURCE)

env.Install(Prefix + '/lib', LibSonotopy)
